on:
    workflow_call:
        inputs:
            dotnet-version: 
                required: true
                type: string
            project:
                required: true
                type: string
            run-coverage:
                required: false
                type: boolean
                default: true

jobs:
    dotnet_build:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ inputs.dotnet-version }}
        
        - name: DotNet Restore
          run: dotnet restore ./src/${{ inputs.project }}
        
        - name: DotNet Build
          run: dotnet build ./src/${{ inputs.project }} --no-restore --configuration Release --verbosity minimal 
        
        - name: DotNet Tests
          run: dotnet test ./test/${{ inputs.project }}.Tests --logger trx --results-directory coverage
        
        - name: Code Coverage Summary Report
          if: inputs.run-coverage
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: 'coverage/*/coverage.cobertura.xml'
            badge: true
            format: 'markdown'
            output: 'both'
    
        - name: Add Coverage PR Comment
          uses: marocchino/sticky-pull-request-comment@v2
          if: inputs.run-coverage && github.event_name == 'pull_request'
          with:
            recreate: true
            path: code-coverage-results.md
    
        - name: Write to Job Summary
          if: inputs.run-coverage
          run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
