on:
    workflow_call:
        inputs:
            dotnet-version: 
                required: true
                type: string

jobs:
    dotnet_build:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ inputs.dotnet-version }}
        
        - name: DotNet Restore
          run: dotnet restore
        
        - name: DotNet Build
          run: dotnet build --no-restore --configuration Release --verbosity minimal 
        
        - name: DotNet Tests
          run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
        
        - name: Code Coverage Summary Report
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: 'coverage/*/coverage.cobertura.xml'
            badge: true
            format: 'markdown'
            output: 'both'
    
        - name: Add Coverage PR Comment
          uses: marocchino/sticky-pull-request-comment@v2
          if: github.event_name == 'pull_request'
          with:
            recreate: true
            path: code-coverage-results.md
    
        - name: Write to Job Summary
          run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
