name: Hypotheek Service

on:
    pull_request:
        branches:
            - main
jobs:
    Build:
        uses: ./.github/workflows/dotnet_build.yml
        with:
            dotnet-version: '8.0'